const {test}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
test('accounts authenticate, protect admin routes and isolate persisted student state',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qalam-auth-'));const port=33000+Math.floor(Math.random()*10000);const base=`http://127.0.0.1:${port}`;const process=spawn(global.process.execPath,['server.js'],{cwd:__dirname,env:{...global.process.env,PORT:String(port),QALAM_HOST:'127.0.0.1',QALAM_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});t.after(()=>{process.kill();});await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Server startup timeout')),8000);process.stdout.on('data',data=>{if(data.toString().includes('ready')){clearTimeout(timeout);resolve();}});process.on('exit',code=>{clearTimeout(timeout);reject(Error('Server exited '+code));});});const request=async(route,method='GET',data,cookie='',origin=base)=>{const r=await fetch(base+'/api/'+route,{method,headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
assert.equal((await request('users')).status,401);
assert.equal((await request('setup','POST',{name:'Librarian',login:'librarian',password:'testing-password-123'})).status,201);
assert.equal((await request('setup','POST',{name:'Other',login:'other',password:'testing-password-123'})).status,400);
assert.equal((await request('login','POST',{login:'librarian',password:'wrong'})).status,401);
const admin=(await request('login','POST',{login:'librarian',password:'testing-password-123'})).cookie;assert.ok(admin);
for(const login of ['student1','student2'])assert.equal((await request('users','POST',{name:login,login,password:'student-password-123'},admin)).status,201);
assert.equal((await request('users','POST',{name:'Dup',login:'student1',password:'student-password-123'},admin)).status,400);
const student=(await request('login','POST',{login:'student1',password:'student-password-123'})).cookie;
assert.equal((await request('users','GET',null,student)).status,403);
assert.equal((await request('catalog','PUT',{books:[],genres:[]},student)).status,403);
assert.equal((await request('logout','POST',{},student,'https://evil.example')).status,403);
const data={shelf:{saved:[1],orders:[2]},preferences:{ratings:{1:5}},engagement:{reviews:{},read:{}}};
assert.equal((await request('state','PUT',data,student)).status,200);
const student2=(await request('login','POST',{login:'student2',password:'student-password-123'})).cookie;
assert.deepEqual((await request('state','GET',null,student2)).data.shelf.saved,[]);
assert.equal((await request('logout','POST',{},student)).status,200);
assert.equal((await request('state','GET',null,student)).status,401);
const again=(await request('login','POST',{login:'student1',password:'student-password-123'})).cookie;
assert.deepEqual((await request('state','GET',null,again)).data,data);

assert.equal((await request('books/1/reviews','POST',{text:'Ортақ пікір <сынақ>'},again)).status,201);
assert.equal((await request('books/1/rating','PUT',{value:5},again)).status,200);
assert.equal((await request('books/1/rating','PUT',{value:3},again)).status,200);
assert.equal((await request('books/1/rating','PUT',{value:5},student2)).status,200);
assert.equal((await request('books/1/rating','PUT',{value:6},student2)).status,400);
assert.equal((await request('books/1/reviews','POST',{text:' '},student2)).status,400);
assert.equal((await request('books/1/reviews','POST',{text:'Anonymous'})).status,401);
const shared=(await request('books/1/community')).data;
assert.equal(shared.reviews[0].text,'Ортақ пікір <сынақ>');assert.equal(shared.reviews[0].name,'student1');assert.equal(shared.count,2);assert.equal(shared.average,4);
const reviewId=shared.reviews[0].id;
assert.equal((await request('admin/reviews','GET',null,student2)).status,403);
assert.equal((await request('admin/reviews/'+reviewId,'PATCH',{visible:false},student2)).status,403);
assert.equal((await request('admin/reviews/'+reviewId,'PATCH',{visible:false},admin)).status,200);
assert.equal((await request('books/1/community')).data.reviews.length,0);
assert.equal((await request('admin/reviews','GET',null,admin)).data[0].visible,0);
assert.equal((await request('admin/reviews/'+reviewId,'PATCH',{visible:true},admin)).status,200);
assert.equal((await request('books/1/community')).data.reviews.length,1);
const {DatabaseSync}=require('node:sqlite');const disk=new DatabaseSync(path.join(dir,'library.sqlite'));assert.equal(disk.prepare('SELECT text FROM reviews WHERE id=?').get(reviewId).text,'Ортақ пікір <сынақ>');assert.equal(disk.prepare('SELECT COUNT(*) n FROM ratings').get().n,2);disk.close();
const restored=spawn(global.process.execPath,['server.js'],{cwd:__dirname,env:{...global.process.env,PORT:String(port+1),QALAM_HOST:'127.0.0.1',QALAM_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});t.after(()=>restored.kill());await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Restore startup timeout')),8000);restored.stdout.on('data',d=>{if(d.toString().includes('ready')){clearTimeout(timer);resolve();}});restored.on('exit',()=>{clearTimeout(timer);reject(Error('Restore failed'));});});const persisted=await fetch(`http://127.0.0.1:${port+1}/api/books/1/community`).then(r=>r.json());assert.equal(persisted.reviews.length,1);assert.equal(persisted.count,2);assert.equal(persisted.average,4);


const schoolBefore=(await request('school','GET',null,again)).data;assert.equal(schoolBefore.students.find(s=>s.name==='student1').score,0);assert.equal(schoolBefore.students.find(s=>s.name==='student1').active,0);
const pupil=schoolBefore.students.find(s=>s.name==='student1').id;
const other=schoolBefore.students.find(s=>s.name==='student2').id;
assert.equal((await request('school')).status,401);
assert.equal((await request('loans?student='+other,'GET',null,again)).status,403);
assert.equal((await request('loans','POST',{student:pupil,book:1},again)).status,403);
const stock=(await request('catalog')).data.books.find(b=>b.id===1).available;
assert.equal((await request('loans','POST',{student:pupil,book:1},admin)).status,201);
assert.equal((await request('catalog')).data.books.find(b=>b.id===1).available,stock-1);
assert.equal((await request('loans','POST',{student:pupil,book:1},admin)).status,400);
const history=(await request('loans?student='+pupil,'GET',null,admin)).data;assert.equal(history[0].status,'borrowed');
assert.equal((await request('school','GET',null,again)).data.students.find(s=>s.id===pupil).score,0);
assert.equal((await request('loans/'+history[0].id+'/return','POST',{},again)).status,403);
assert.equal((await request('loans/'+history[0].id+'/return','POST',{},admin)).status,200);
assert.equal((await request('loans/'+history[0].id+'/return','POST',{},admin)).status,400);
assert.equal((await request('catalog')).data.books.find(b=>b.id===1).available,stock);
assert.equal((await request('school','GET',null,again)).data.students.find(s=>s.id===pupil).score,10);
assert.equal((await request('loans','POST',{student:pupil,book:1},admin)).status,201);
const repeated=(await request('loans?student='+pupil,'GET',null,admin)).data[0];
await request('loans/'+repeated.id+'/return','POST',{},admin);
assert.equal((await request('school','GET',null,again)).data.students.find(s=>s.id===pupil).score,10);

assert.equal((await request('survey')).status,401);
assert.equal((await request('survey/results','GET',null,again)).status,403);
const beforeSurvey={stage:'before',answers:{interest:2,finding:2,books:1,motivation:2}};
assert.equal((await request('survey','PUT',beforeSurvey,again)).status,200);
beforeSurvey.answers.interest=3;assert.equal((await request('survey','PUT',beforeSurvey,again)).status,200);
assert.equal((await request('survey','PUT',{stage:'after',answers:{interest:4,finding:5,books:3,motivation:5,favorite:'quiz',suggestion:'Жақсы <сынақ>'}},again)).status,200);
assert.equal((await request('survey','PUT',{stage:'before',answers:{interest:7,finding:1,books:0,motivation:1}},again)).status,400);
const summary=(await request('survey/results','GET',null,admin)).data;assert.equal(summary.before.count,1);assert.equal(summary.after.count,1);assert.equal(summary.paired,1);assert.equal(summary.changes.interest,1);assert.equal(summary.favorites.quiz,1);assert.equal(summary.suggestions[0],'Жақсы <сынақ>');
assert.equal((await request('survey','GET',null,student2)).data.length,0);
const restoredSurvey=await fetch(`http://127.0.0.1:${port+1}/api/survey/results`,{headers:{Cookie:admin}}).then(r=>r.json());assert.equal(restoredSurvey.paired,1);
});
