let account=null;
let accountReady=false;
let setupRequired=false;
let syncTimer;
let syncQueue=Promise.resolve();
const serverMode=location.protocol==='http:'||location.protocol==='https:';
async function api(route,method='GET',data){const response=await fetch('/api/'+route,{method,credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const value=await response.json();if(!response.ok)throw Error(value.error||'Сервер қатесі');return value;}
function resetPersonal(){state={saved:[],orders:[]};preferences={name:'',font:18,theme:'light',progress:{},ratings:{}};engagement={reviews:{},read:{}};}
function queueSync(){if(!serverMode||!accountReady||!account)return;clearTimeout(syncTimer);const owner=account.id;syncTimer=setTimeout(()=>{const data=JSON.parse(JSON.stringify({shelf:state,preferences,engagement}));syncQueue=syncQueue.then(()=>{if(account?.id!==owner)return;return api('state','PUT',data);}).catch(e=>toast(e.message));},150);}
if(serverMode){persist=function(){document.querySelector('#shelf-count').textContent=new Set([...state.saved,...state.orders]).size;queueSync();};remember=queueSync;saveEngagement=queueSync;saveCatalog=function(){if(account?.role!=='admin'){toast('Кітапханашы аккаунтымен кіріңіз.');return false;}api('catalog','PUT',{books,genres:customGenres}).catch(e=>toast('Серверге сақталмады: '+e.message));return true;};resetPersonal();render();challengeSummary();document.querySelector('#admin-open').hidden=true;}
async function loadAccount(){accountReady=false;const session=await api('session');account=session.user;setupRequired=session.setupRequired;const c=await api('catalog');books.splice(0,books.length,...c.books);customGenres=c.genres;resetPersonal();if(account){const v=await api('state');const ids=new Set(books.map(b=>b.id));state={saved:(v.shelf?.saved||[]).filter(id=>ids.has(id)),orders:(v.shelf?.orders||[]).filter(id=>ids.has(id))};preferences={...preferences,...v.preferences,name:account.name};engagement={...engagement,...v.engagement};}refreshGenres();render();challengeSummary();document.querySelector('#admin-open').hidden=account?.role!=='admin';document.querySelector('#profile-open').textContent=account?'Менің аккаунтым':'Кіру';accountReady=true;}
function loginPanel(){feature(`<div class="eyebrow">ОҚЫРМАН АККАУНТЫ</div><h2>${setupRequired?'Алғашқы кітапханашы':'Аккаунтқа кіру'}</h2><p>${setupRequired?'Бірінші әкімшіні сервер орналасқан компьютерден жасаңыз. Одан кейін оқушы аккаунттарын әкімші ашады.':'Логин мен құпиясөзді кітапханашы береді.'}</p><form id="account-login" class="quiz-form">${setupRequired?'<label>Аты<input name="name" required maxlength="60"></label>':''}<label>Логин<input name="login" required minlength="3" maxlength="40" autocomplete="username" pattern="[a-zA-Z0-9_.-]{3,40}"></label><label>Құпиясөз<input name="password" required type="password" minlength="8" maxlength="128" autocomplete="${setupRequired?'new-password':'current-password'}"></label><p id="account-error" role="alert"></p><button class="primary">${setupRequired?'Әкімші аккаунтын жасау':'Кіру'}</button></form>`);document.querySelector('#account-login').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if(setupRequired)await api('setup','POST',data);await api('login','POST',data);await loadAccount();accountPanel();}catch(error){document.querySelector('#account-error').textContent=error.message;button.disabled=false;}};}
function accountPanel(){if(!serverMode){feature('<h2>Сервер қажет</h2><p>Нақты аккаунттар HTML файлын жеке ашқанда жұмыс істемейді. Сайтты npm start арқылы іске қосыңыз.</p>');return;}if(!account){loginPanel();return;}feature(`<div class="eyebrow">${account.role==='admin'?'КІТАПХАНАШЫ':'ОҚУШЫ'}</div><h2>${htmlSafe(account.name)}</h2><p>Логин: ${htmlSafe(account.login)}</p><div class="profile-stats"><span><strong>${state.saved.length}</strong>Сақталған кітап</span><span><strong>${state.orders.length}</strong>Брондау</span><span><strong>${readIds().length}</strong>Осы айда оқылды</span></div><button class="secondary" id="account-logout">Аккаунттан шығу</button>${account.role==='admin'?'<section class="admin-section"><h3>Оқушы аккаунтын ашу</h3><form id="student-create" class="quiz-form"><label>Оқушы аты<input name="name" required maxlength="60"></label><label>Логин<input name="login" required minlength="3" maxlength="40" pattern="[a-zA-Z0-9_.-]{3,40}" autocomplete="off"></label><label>Бастапқы құпиясөз<input name="password" type="password" required minlength="8" maxlength="128" autocomplete="new-password"></label><button class="primary">Аккаунт ашу</button><p id="student-message" role="status"></p></form><h3>Оқушылар</h3><div id="student-list"></div></section>':''}`);document.querySelector('#account-logout').onclick=async()=>{try{clearTimeout(syncTimer);await syncQueue;if(accountReady)await api('state','PUT',{shelf:state,preferences,engagement});await api('logout','POST',{});await loadAccount();loginPanel();}catch(e){toast(e.message);}};if(account.role==='admin'){const list=()=>api('users').then(users=>document.querySelector('#student-list').innerHTML=users.map(u=>`<div class="author-row"><span>${htmlSafe(u.name)}</span><small>${htmlSafe(u.login)} · ${u.role==='admin'?'Кітапханашы':'Оқушы'}</small></div>`).join('')).catch(e=>toast(e.message));list();document.querySelector('#student-create').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('users','POST',Object.fromEntries(new FormData(e.target)));e.target.reset();document.querySelector('#student-message').textContent='Оқушы аккаунты ашылды. Логин мен құпиясөзді оқушыға жеке беріңіз.';list();}catch(error){document.querySelector('#student-message').textContent=error.message;}finally{button.disabled=false;}};}}
document.querySelector('#profile-open').onclick=accountPanel;
if(serverMode){document.addEventListener('click',e=>{if(e.target.closest('#admin-open,[data-edit-book]')&&account?.role!=='admin'){e.stopImmediatePropagation();e.preventDefault();loginPanel();return;}if(e.target.closest('[data-save],[data-order],[data-remove],[data-finished],[data-unread]')&&!account){e.stopImmediatePropagation();e.preventDefault();loginPanel();}},true);document.addEventListener('submit',e=>{if(e.target.id==='review-form'&&!account){e.stopImmediatePropagation();e.preventDefault();loginPanel();}},true);document.addEventListener('change',e=>{if(e.target.matches('[data-rating]')&&!account){e.stopImmediatePropagation();loginPanel();}},true);const oldReader=reader;reader=function(...args){if(!account){loginPanel();return;}return oldReader(...args);};loadAccount().catch(e=>toast('Аккаунт сервері қолжетімсіз: '+e.message));}

if(serverMode){const accountBook=openBook;openBook=function(id){accountBook(id);const note=document.querySelector('.reviews .dialog-note');if(note)note.textContent='Бұл аккаунттың жеке пікірлері. Басқа оқушыларға әзірге көрінбейді.';};document.querySelector('#shelf-dialog .dialog-note').textContent='Жеке сөре мен демо брондаулар аккаунтыңызда серверге сақталады.';}
