const {test}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
test('accounts authenticate, protect admin routes and isolate persisted student state',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qalam-auth-'));const port=33000+Math.floor(Math.random()*10000);const base=`http://127.0.0.1:${port}`;const process=spawn(global.process.execPath,['server.js'],{cwd:__dirname,env:{...global.process.env,PORT:String(port),QALAM_HOST:'127.0.0.1',QALAM_DATA_DIR:dir},stdio:['ignore','pipe','pipe']});t.after(()=>{process.kill();});await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Server startup timeout')),8000);process.stdout.on('data',data=>{if(data.toString().includes('ready')){clearTimeout(timeout);resolve();}});process.on('exit',code=>{clearTimeout(timeout);reject(Error('Server exited '+code));});});const request=async(route,method='GET',data,cookie='',origin=base)=>{const r=await fetch(base+'/api/'+route,{method,headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
assert.equal((await request('users')).status,401);
assert.equal((await request('setup','POST',{name:'Librarian',login:'librarian',password:'testing-password-123'})).status,201);
assert.equal((await request('setup','POST',{name:'Other',login:'other',password:'testing-password-123'})).status,400);
assert.equal((await request('login','POST',{login:'librarian',password:'wrong'})).status,401);
const admin=(await request('login','POST',{login:'librarian',password:'testing-password-123'})).cookie;assert.ok(admin);
for(const login of ['student1','student2'])assert.equal((await request('users','POST',{name:login,login,password:'student-password-123'},admin)).status,201);
assert.equal((await request('users','POST',{name:'Dup',login:'student1',password:'student-password-123'},admin)).status,400);
const student=(await request('login','POST',{login:'student1',password:'student-password-123'})).cookie;
assert.equal((await request('users','GET',null,student)).status,403);
assert.equal((await request('catalog','PUT',{books:[],genres:[]},student)).status,403);
assert.equal((await request('logout','POST',{},student,'https://evil.example')).status,403);
const data={shelf:{saved:[1],orders:[2]},preferences:{ratings:{1:5}},engagement:{reviews:{},read:{}}};
assert.equal((await request('state','PUT',data,student)).status,200);
const student2=(await request('login','POST',{login:'student2',password:'student-password-123'})).cookie;
assert.deepEqual((await request('state','GET',null,student2)).data.shelf.saved,[]);
assert.equal((await request('logout','POST',{},student)).status,200);
assert.equal((await request('state','GET',null,student)).status,401);
const again=(await request('login','POST',{login:'student1',password:'student-password-123'})).cookie;
assert.deepEqual((await request('state','GET',null,again)).data,data);
});
