const originalCover=cover;
cover=function(b){return originalCover({...b,author:htmlSafe(b.author),cover:htmlSafe(b.cover),label:htmlSafe(b.label)});};
function allGenres(){return [...new Set(['Қазақ әдебиеті','Әлем әдебиеті','Ғылым','Балаларға',...customGenres,...books.map(b=>b.genre)])];}
function refreshGenres(){document.querySelector('.filters').innerHTML=['Барлығы',...allGenres()].map(g=>`<button data-genre="${htmlSafe(g)}" class="${g===genre?'selected':''}" aria-pressed="${g===genre}">${htmlSafe(g)}</button>`).join('');}
function saveCatalog(){try{localStorage.setItem('qalam-admin-catalog',JSON.stringify({books,genres:customGenres}));return true;}catch{toast('Сақтау мүмкін болмады. Өзгерістер тек осы сессияда қалады.');return false;}}
const adminDialog=document.createElement('dialog');adminDialog.id='admin-dialog';adminDialog.innerHTML='<button class="close" aria-label="Жабу">×</button><div id="admin-content"></div>';document.body.append(adminDialog);
document.querySelector('header nav').insertAdjacentHTML('beforeend','<button class="nav-feature" id="admin-open">Админ панель</button>');
function adminPanel(){document.querySelector('#admin-content').innerHTML=`<div class="eyebrow">КІТАПХАНАНЫ БАСҚАРУ</div><h2>Админ панель</h2><p class="dialog-note">Жергілікті демонстрациялық панель. Кіру шектеуі жоқ; өзгерістер тек осы браузерде сақталады.</p><section class="admin-section"><h3>Жаңа жанр</h3><form id="genre-form" class="admin-inline"><input id="new-genre" required maxlength="60" placeholder="Жанр атауы" aria-label="Жаңа жанр атауы"><button class="primary">Қосу</button></form><p id="genre-message" role="status"></p></section><section class="admin-section"><h3 id="book-form-title">Жаңа кітап</h3><form id="admin-book-form"><input id="edit-id" type="hidden"><div class="admin-fields"><label>Кітап атауы<input id="new-title" required maxlength="120"></label><label>Автор<input id="new-author" required maxlength="100"></label><label>Жанр<select id="new-book-genre">${allGenres().map(g=>`<option>${htmlSafe(g)}</option>`).join('')}</select></label><label>Жылы<input id="new-year" type="number" min="1" max="2100" value="2026" required></label><label>Жалпы дана саны<input id="new-total" type="number" min="0" max="100000" step="1" value="1" required></label><label>Оқырмандарда<input id="new-borrowed" type="number" min="0" max="100000" step="1" value="0" required></label></div><p id="available-preview">Кітапханада: 1 дана</p><label>Сипаттама<textarea id="new-description" maxlength="2000" rows="3" required></textarea></label><p id="book-message" role="status"></p><div class="feature-actions"><button class="primary" type="submit">Сақтау</button><button class="secondary" id="cancel-edit" type="button">Тазалау</button></div></form></section><section class="admin-section"><h3>Кітап қоры · ${books.length} кітап</h3><label class="search"><input id="admin-search" type="search" placeholder="Атау немесе автор бойынша іздеу" aria-label="Админ кітап іздеу"></label><div id="admin-books"></div></section>`;drawAdminBooks();document.querySelector('#genre-form').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#new-genre').value.trim();if(!name)return;if(allGenres().some(g=>g.toLocaleLowerCase()===name.toLocaleLowerCase())){document.querySelector('#genre-message').textContent='Бұл жанр бұрыннан бар.';return;}customGenres.push(name);saveCatalog();refreshGenres();adminPanel();toast('Жаңа жанр қосылды');};document.querySelector('#admin-book-form').onsubmit=submitBook;document.querySelector('#cancel-edit').onclick=adminPanel;document.querySelector('#admin-search').oninput=drawAdminBooks;for(const id of ['new-total','new-borrowed'])document.getElementById(id).oninput=()=>{const n=Number(document.querySelector('#new-total').value)-Number(document.querySelector('#new-borrowed').value);document.querySelector('#available-preview').textContent=n>=0?`Кітапханада: ${n} дана`:'Оқырмандардағы сан жалпы саннан артық болмауы керек.';};if(!adminDialog.open)adminDialog.showModal();}
function drawAdminBooks(){const q=document.querySelector('#admin-search').value.toLocaleLowerCase().trim();const list=books.filter(b=>`${b.title} ${b.author}`.toLocaleLowerCase().includes(q));document.querySelector('#admin-books').innerHTML=list.map(b=>`<div class="admin-book-row"><div><strong>${htmlSafe(b.title)}</strong><small>${htmlSafe(b.author)} · ${htmlSafe(b.genre)}</small><small>Барлығы: ${b.total} · Кітапханада: ${b.available} · Оқырмандарда: ${b.total-b.available}</small></div><button class="secondary" data-edit-book="${b.id}">Өзгерту</button></div>`).join('')||'<p>Кітап табылмады.</p>';}
function submitBook(e){e.preventDefault();const id=Number(document.querySelector('#edit-id').value);const total=Number(document.querySelector('#new-total').value);const borrowed=Number(document.querySelector('#new-borrowed').value);const title=document.querySelector('#new-title').value.trim();const author=document.querySelector('#new-author').value.trim();const description=document.querySelector('#new-description').value.trim();if(!title||!author||!description||!Number.isInteger(total)||!Number.isInteger(borrowed)||total<0||borrowed<0||borrowed>total){document.querySelector('#book-message').textContent='Деректерді тексеріңіз: оқырмандардағы сан жалпы саннан аспауы керек.';return;}const existing=books.find(b=>b.id===id);const book={...(existing||{id:Math.max(0,...books.map(b=>b.id))+1,color:'forest',label:'КІТАПХАНА ҚОРЫ'}),title,author,description,genre:document.querySelector('#new-book-genre').value,year:Number(document.querySelector('#new-year').value),total,available:total-borrowed,cover:title.toLocaleUpperCase()};if(existing)Object.assign(existing,book);else books.push(book);saveCatalog();refreshGenres();render();adminPanel();toast(existing?'Кітап деректері жаңартылды':'Жаңа кітап қосылды');}
document.querySelector('#admin-open').onclick=adminPanel;
document.addEventListener('click',e=>{const btn=e.target.closest('[data-edit-book]');if(!btn)return;const b=books.find(b=>b.id===Number(btn.dataset.editBook));document.querySelector('#edit-id').value=b.id;document.querySelector('#book-form-title').textContent='Кітапты өзгерту';for(const [id,value] of Object.entries({'new-title':b.title,'new-author':b.author,'new-year':b.year,'new-book-genre':b.genre,'new-total':b.total,'new-borrowed':b.total-b.available,'new-description':b.description}))document.getElementById(id).value=value;document.querySelector('#available-preview').textContent=`Кітапханада: ${b.available} дана`;document.querySelector('#book-form-title').scrollIntoView({behavior:'smooth',block:'start'});});
refreshGenres();render();
