let genre='Барлығы';
let state={saved:[],orders:[]};
try{const stored=JSON.parse(localStorage.getItem('qalam-library')||'null');if(stored&&Array.isArray(stored.saved)&&Array.isArray(stored.orders)){state.saved=stored.saved.filter(id=>books.some(b=>b.id===id));state.orders=stored.orders.filter(id=>books.some(b=>b.id===id));}}catch{}
const grid=document.querySelector('#book-grid');
let toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2800);}
function persist(){try{localStorage.setItem('qalam-library',JSON.stringify(state));}catch{toast('Браузерде сақтау қолжетімсіз. Таңдауыңыз осы сессияда сақталады.');}document.querySelector('#shelf-count').textContent=new Set([...state.saved,...state.orders]).size;}
function cover(b){return `<div class="cover ${b.color}"><small>${b.author.toLocaleUpperCase()}</small><strong>${b.cover}</strong><span>${b.label}</span></div>`;}
function render(){const list=filterBooks(document.querySelector('#search').value,genre);document.querySelector('#results-count').textContent=`${list.length} кітап`;document.querySelector('#empty').hidden=list.length>0;grid.innerHTML=list.map(b=>`<article class="book-card"><div class="cover-wrap"><button class="save ${state.saved.includes(b.id)?'saved':''}" data-save="${b.id}" aria-label="${htmlSafe(b.title)}: сөреге сақтау" aria-pressed="${state.saved.includes(b.id)}">${state.saved.includes(b.id)?'♥':'♡'}</button><button class="cover-open" data-open="${b.id}" aria-label="${htmlSafe(b.title)} туралы">${cover(b)}</button></div><span class="genre">${htmlSafe(b.genre)}</span><button class="book-title" data-open="${b.id}">${htmlSafe(b.title)}</button><p class="author">${htmlSafe(b.author)}</p><div class="book-meta"><span>${b.available>0?`● ${b.available} дана қолжетімді`:'○ Қазір кітапханада жоқ'}</span><button data-open="${b.id}">Толығырақ ↗</button></div></article>`).join('');persist();}
function save(id){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];render();renderShelf();}
function openBook(id){const b=books.find(b=>b.id===id);const ordered=state.orders.includes(id);document.querySelector('#book-detail').innerHTML=`<div class="detail-cover">${cover(b)}</div><h2>${htmlSafe(b.title)}</h2><div class="eyebrow">${htmlSafe(b.genre)} · ${b.year}</div><p>${htmlSafe(b.author)}</p><p>${htmlSafe(b.description)}</p><section class="inventory" aria-label="Кітап қоры"><h3>Кітапхана қоры</h3><div class="inventory-grid"><div><strong>${b.total}</strong><span>Жалпы дана саны</span></div><div><strong>${b.available}</strong><span>Кітапханада</span></div><div><strong>${b.total-b.available}</strong><span>Оқырмандарда</span></div></div><p class="inventory-note">Демонстрациялық деректер · Нақты кітапхана есебіне қосылмаған</p></section><p class="dialog-note">Толық мәтін ұсынылмайды. Бұл каталог кітап таңдау мен тапсырыс беруді көрсетеді.</p><div class="detail-actions"><button class="primary" data-order="${id}" ${ordered||b.available===0?'disabled':''}>${ordered?'Брондау сақталды ✓':b.available===0?'Қолжетімді дана жоқ':'Демо брондау'}</button><button class="secondary" data-save="${id}">${state.saved.includes(id)?'Сөреден алып тастау':'Сөреге сақтау'}</button></div>`;const d=document.querySelector('#book-dialog');if(!d.open)d.showModal();}
function renderShelf(){const ids=[...new Set([...state.saved,...state.orders])];document.querySelector('#shelf-list').innerHTML=ids.length?ids.map(id=>{const b=books.find(b=>b.id===id);return `<div class="shelf-row"><div><strong>${htmlSafe(b.title)}</strong><small>${htmlSafe(b.author)}</small><small>${state.orders.includes(id)?'✓ Демо тапсырыс сақталды':'♡ Жеке сөреде'}</small></div><button data-remove="${id}" aria-label="${htmlSafe(b.title)}: сөреден және тапсырыстан жою">Жою</button></div>`;}).join(''):'<p>Сөреңіз әзірге бос. Каталогтан ұнаған кітапты сақтаңыз.</p>';}
document.querySelector('#search').addEventListener('input',render);
document.querySelector('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-genre]');if(!b)return;genre=b.dataset.genre;document.querySelectorAll('[data-genre]').forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',String(el===b));});render();});
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)openBook(Number(open.dataset.open));const saved=e.target.closest('[data-save]');if(saved){const id=Number(saved.dataset.save);save(id);if(document.querySelector('#book-dialog').open)openBook(id);}const order=e.target.closest('[data-order]');if(order){const id=Number(order.dataset.order);if(!books.find(b=>b.id===id)?.available)return;if(!state.orders.includes(id))state.orders.push(id);persist();renderShelf();openBook(id);toast('Демо брондау сақталды');}const remove=e.target.closest('[data-remove]');if(remove){const id=Number(remove.dataset.remove);state.saved=state.saved.filter(x=>x!==id);state.orders=state.orders.filter(x=>x!==id);render();renderShelf();}if(e.target.closest('.close'))e.target.closest('dialog').close();});
document.querySelector('#shelf-open').addEventListener('click',()=>{renderShelf();document.querySelector('#shelf-dialog').showModal();});
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
document.querySelectorAll('[data-genre]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.genre===genre)));
render();
