if(serverMode){
const communityBook=openBook;
openBook=function(id){communityBook(id);const rating=document.querySelector('.rating');rating.insertAdjacentHTML('afterbegin','<div id="public-rating" role="status">Бағалар жүктелуде…</div>');rating.querySelector('small').textContent='Әр аккаунт бір баға береді. Бағалар барлық оқырманға көрінеді.';const section=document.querySelector('.reviews');section.innerHTML=`<h3>Оқырман пікірлері</h3><p class="dialog-note">Пікір мен аккаунттағы атыңыз барлық оқырманға көрінеді. Әкімші пікірді жасыра алады.</p><div id="public-reviews" role="status">Пікірлер жүктелуде…</div>${account?'<form id="review-form"><label>Қысқа пікір<textarea name="text" maxlength="500" rows="3" required placeholder="Кітаптан алған әсеріңмен бөліс"></textarea></label><p id="review-error" role="alert"></p><button class="primary" type="submit">Пікір қалдыру</button></form>':'<p>Пікір қалдыру үшін аккаунтқа кіріңіз.</p>'}`;const refresh=async()=>{try{const data=await api(`books/${id}/community`);if(!section.isConnected)return;rating.querySelector('#public-rating').innerHTML=`<strong>★ ${data.count?data.average.toFixed(1):'—'} / 5</strong> · ${data.count} баға<details><summary>Оқырман бағалары</summary>${data.ratings.map(r=>`<p>${htmlSafe(r.name)} · ${'★'.repeat(r.value)} (${r.value}/5)</p>`).join('')||'<p>Әзірге баға жоқ.</p>'}</details>`;rating.querySelector('select').value=String(data.mine);section.querySelector('#public-reviews').innerHTML=data.reviews.map(r=>`<article class="review"><strong>${htmlSafe(r.name)}</strong><p>${htmlSafe(r.text)}</p></article>`).join('')||'<p>Алғашқы пікірді сен қалдыр!</p>';}catch(e){if(section.isConnected){section.querySelector('#public-reviews').textContent=e.message;rating.querySelector('#public-rating').textContent='Бағаларды жүктеу мүмкін болмады.';}}};const form=section.querySelector('form');if(form)form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('button');btn.disabled=true;try{await api(`books/${id}/reviews`,'POST',{text:form.elements.text.value});form.reset();await refresh();toast('Пікір жарияланды');}catch(error){form.querySelector('#review-error').textContent=error.message;}finally{btn.disabled=false;}};refresh();};
// Stop the former private-rating handler; the select's target listener saves to the shared API.

// Delegated capture cannot allow the target listener when stopped: handle public ratings here instead.
document.addEventListener('change',async e=>{if(!e.target.matches('[data-rating]')||!account)return;e.stopImmediatePropagation();const select=e.target;select.disabled=true;try{await api(`books/${select.dataset.rating}/rating`,'PUT',{value:Number(select.value)});openBook(Number(select.dataset.rating));toast('Баға сақталды');}catch(error){toast(error.message);openBook(Number(select.dataset.rating));}finally{select.disabled=false;}},true);
const originalAdminPanel=adminPanel;
adminPanel=function(){originalAdminPanel();document.querySelector('#admin-content').insertAdjacentHTML('beforeend','<section class="admin-section"><h3>Пікірлерді басқару</h3><p>Жасырылған пікірлер оқырмандарға көрінбейді. «Қайта көрсету» арқылы қалпына келтіруге болады.</p><div id="moderation-list" role="status">Жүктелуде…</div></section>');loadModeration();};
async function loadModeration(){const el=document.querySelector('#moderation-list');if(!el)return;try{const list=await api('admin/reviews');if(!el.isConnected)return;el.innerHTML=list.map(r=>`<article class="review"><strong>${htmlSafe(r.name)} · ${htmlSafe(books.find(b=>b.id===r.book_id)?.title||'Кітап')}</strong><p>${htmlSafe(r.text)}</p><small>${r.visible?'Жарияланған':'Жасырылған'}</small><br><button class="secondary" data-moderate="${r.id}" data-visible="${r.visible?'false':'true'}">${r.visible?'Пікірді өшіру (жасыру)':'Қайта көрсету'}</button></article>`).join('')||'<p>Әзірге пікір жоқ.</p>';}catch(e){el.textContent=e.message;}}
document.querySelector('#admin-open').onclick=adminPanel;
document.addEventListener('click',async e=>{const b=e.target.closest('[data-moderate]');if(!b)return;b.disabled=true;try{await api(`admin/reviews/${b.dataset.moderate}`,'PATCH',{visible:b.dataset.visible==='true'});await loadModeration();}catch(error){toast(error.message);b.disabled=false;}});
}
