let engagement={reviews:{},read:{}};
try{const saved=JSON.parse(localStorage.getItem('qalam-engagement'));if(saved&&saved.reviews&&saved.read)engagement=saved;}catch{}
function saveEngagement(){try{localStorage.setItem('qalam-engagement',JSON.stringify(engagement));}catch{toast('Өзгерістер тек осы сессияда сақталады.');}}
function monthKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
function readIds(){return Array.isArray(engagement.read[monthKey()])?engagement.read[monthKey()]:[];}
const studentSection=document.createElement('section');studentSection.className='student-section';studentSection.innerHTML='<div><div class="eyebrow">ОҚУДЫ ӨЗІҢНЕН БАСТА</div><h2>Саған қай кітап сай келеді?</h2><p>4 қысқа сұраққа жауап бер. Қызығушылығыңа сай кітаптарды бірге табайық.</p><button class="primary" id="quiz-open">Маған кітап таңда ↗</button></div><div id="challenge-summary"></div>';document.querySelector('.catalog').before(studentSection);
function challengeSummary(){const count=readIds().length;document.querySelector('#challenge-summary').innerHTML=`<div class="eyebrow">ОСЫ АЙДЫҢ CHALLENGE-І</div><h3>Осы айда 3 кітап оқы</h3><div class="challenge-track" role="progressbar" aria-label="Осы айда оқылған кітаптар" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${Math.min(count,3)}"><span style="width:${Math.min(count/3,1)*100}%"></span></div><p>${count} / 3 кітап · ${count>=3?'Мақсат орындалды! 🏅':'Әр кітап — алға бір қадам'}</p><button class="secondary" id="challenge-open">Оқу жетістіктерім</button>`;document.querySelector('#challenge-open').onclick=challenge;}
function challenge(){const ids=readIds();const total=[...new Set(Object.values(engagement.read).filter(Array.isArray).flat())].length;feature(`<div class="eyebrow">ОҚУ CHALLENGE</div><h2>Осы айда 3 кітап оқы</h2><p>Кітапты оқып бітірген соң, оның бетіндегі «Оқып бітірдім» батырмасын бас. Бұл өзің белгілейтін оқу есебі.</p><h3>${ids.length} / 3 кітап</h3><div class="badges"><span class="${total>=1?'earned':''}">✦ Алғашқы кітап</span><span class="${total>=5?'earned':''}">★ 5 кітап оқыды</span><span class="${ids.length>=3?'earned':''}">🏅 Ай мақсаты</span></div>${ids.map(id=>books.find(b=>b.id===id)).filter(Boolean).map(b=>`<div class="author-row"><span>${htmlSafe(b.title)}</span><button class="secondary" data-unread="${b.id}">Белгіні алу</button></div>`).join('')||'<p>Осы айда оқылған кітаптар әзірге белгіленбеген.</p>'}`);}
function quiz(){feature(`<div class="eyebrow">4 СҰРАҚ · ЖЕКЕ ҰСЫНЫС</div><h2>Маған кітап таңда</h2><form id="quiz-form" class="quiz-form"><label>1. Жасың қанша?<select name="age"><option value="young">10–12 жас</option><option value="teen" selected>13–15 жас</option><option value="older">16 жастан жоғары</option></select></label><label>2. Қай жанр ұнайды?<select name="genre"><option value="any">Кез келген</option>${allGenres().map(g=>`<option value="${htmlSafe(g)}">${htmlSafe(g)}</option>`).join('')}</select></label><label>3. Не қызықтырады?<select name="interest"><option value="adventure">Қызықты оқиғалар</option><option value="history">Тарих пен ұлттық мұра</option><option value="science">Ғылым және ғалам</option><option value="thought">Өмір туралы ойлану</option></select></label><label>4. Қазір кітапханада бар кітап керек пе?<select name="available"><option value="yes">Иә, қолжетімді кітап</option><option value="any">Барлық кітапты ұсын</option></select></label><button class="primary" type="submit">Кітаптарды ұсын ↗</button></form>`);document.querySelector('#quiz-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const candidates=books.filter(b=>data.available!=='yes'||b.available>0);const scored=candidates.map(b=>{let score=0;const reasons=[];if(data.genre===b.genre){score+=6;reasons.push('таңдаған жанрыңа сәйкес');}if(data.age==='young'&&b.genre==='Балаларға'){score+=3;reasons.push('жас оқырманға арналған');}const desired={adventure:['Балаларға','Әлем әдебиеті'],history:['Қазақ әдебиеті'],science:['Ғылым'],thought:['Әлем әдебиеті','Қазақ әдебиеті']}[data.interest];if(desired.includes(b.genre)){score+=3;reasons.push('қызығушылығыңа жақын');}return {b,score,reasons};}).sort((a,b)=>b.score-a.score||a.b.id-b.b.id).slice(0,3);feature(`<div class="eyebrow">СЕНІҢ ТАҢДАУЫҢ</div><h2>Саған ұсынылатын кітаптар</h2><p>Бұл ұсыныс жанр мен қызығушылыққа негізделген қарапайым ереже арқылы жасалады. Жас бойынша нақты сараптамалық жіктеу емес.</p>${scored.map(({b,reasons})=>`<button class="author-row" data-feature-book="${b.id}"><span><strong>${htmlSafe(b.title)}</strong><small style="display:block;margin-top:6px">${htmlSafe(reasons.join(', ')||'Каталогтағы балама кітап')}</small></span><small>Ашу →</small></button>`).join('')||'<p>Қолжетімді кітап жоқ. Каталогты кейінірек тексер.</p>'}<button class="secondary" id="quiz-retry" style="margin-top:20px">Қайта таңдау</button>`);document.querySelector('#quiz-retry').onclick=quiz;};}
document.querySelector('#quiz-open').onclick=quiz;
const beforeEngagement=openBook;
openBook=function(id){beforeEngagement(id);const reviews=Array.isArray(engagement.reviews[id])?engagement.reviews[id]:[];const read=readIds().includes(id);document.querySelector('#book-detail').insertAdjacentHTML('beforeend',`<div class="feature-actions"><button class="secondary" data-finished="${id}">${read?'✓ Осы айда оқылды':'Оқып бітірдім'}</button></div><section class="reviews"><h3>Оқырман пікірлері</h3><p class="dialog-note">Пікірлер осы браузерде ғана сақталады. Басқа оқушыларға жіберілмейді.</p><div>${reviews.map(r=>`<article class="review"><strong>${htmlSafe(r.name)}</strong><p>${htmlSafe(r.text)}</p></article>`).join('')||'<p>Алғашқы пікірді сен қалдыр!</p>'}</div><form id="review-form"><label>Атың<input name="name" maxlength="60" required value="${htmlSafe(preferences.name)}"></label><label>Қысқа пікір<textarea name="text" maxlength="500" rows="3" required placeholder="Кітаптан алған әсеріңмен бөліс"></textarea></label><button class="primary" type="submit">Пікір қалдыру</button></form></section>`);document.querySelector('#review-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.name.trim()||!data.text.trim())return;if(!Array.isArray(engagement.reviews[id]))engagement.reviews[id]=[];engagement.reviews[id].push({name:data.name.trim().slice(0,60),text:data.text.trim().slice(0,500)});saveEngagement();openBook(id);toast('Пікір сақталды');};};
document.addEventListener('click',e=>{const done=e.target.closest('[data-finished]');if(done){const id=Number(done.dataset.finished);if(!Array.isArray(engagement.read[monthKey()]))engagement.read[monthKey()]=[];if(!readIds().includes(id))engagement.read[monthKey()].push(id);saveEngagement();challengeSummary();openBook(id);toast('Оқылған кітап белгіленді');}const undone=e.target.closest('[data-unread]');if(undone){engagement.read[monthKey()]=readIds().filter(id=>id!==Number(undone.dataset.unread));saveEngagement();challengeSummary();challenge();}});
challengeSummary();
