// Local demonstration features. No remote account or published book content.
let preferences={name:'',font:18,theme:'light',progress:{},ratings:{}};
try{const v=JSON.parse(localStorage.getItem('qalam-preferences'));if(v&&typeof v==='object')preferences={...preferences,...v};}catch{}
function remember(){try{localStorage.setItem('qalam-preferences',JSON.stringify(preferences));}catch{toast('Баптаулар тек осы сессияда сақталады.');}}
function escapeText(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const samplePages=[
 'Бұл — онлайн оқу мүмкіндігін таныстыратын демонстрациялық мәтін. Мұнда оқырман қаріп өлшемін өзгертіп, күндізгі немесе түнгі режимді таңдап, оқыған бетін сақтай алады. Бұл мәтін таңдалған кітаптың түпнұсқасы емес.',
 'Кітапхана қорын цифрландыру оқырманның уақытын үнемдейді. Электрондық каталог арқылы кітап атауын, авторын және қолжетімді дана санын көруге болады. Қор есебі нақты дерекқорға қосылған кезде кітап беру мен қайтару деректері жаңартылып отырады.',
 'Оқу мәдениеті күнделікті шағын қадамдардан басталады. Ұнаған кітапты жеке сөреге сақтап, келесі оқуға жоспарлауға болады. Бұл демонстрациядағы оқу барысы мен баға осы браузерде ғана сақталады.'
];
const extra=document.createElement('dialog');extra.id='feature-dialog';extra.innerHTML='<button class="close" aria-label="Жабу">×</button><div id="feature-content"></div>';document.body.append(extra);
function feature(html){if('speechSynthesis'in window)window.speechSynthesis.cancel();document.querySelector('#feature-content').innerHTML=html;if(!extra.open)extra.showModal();}
extra.addEventListener('close',()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel();});
extra.addEventListener('click',e=>{if(e.target===extra){const r=extra.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)extra.close();}});
const originalOpenBook=openBook;
openBook=function(id){originalOpenBook(id);const b=books.find(b=>b.id===id);document.querySelector('#book-detail').insertAdjacentHTML('beforeend',`<div class="feature-actions"><button class="secondary" data-read="${id}">▤ Оқу демосы</button><button class="secondary" data-audio="${id}">◉ Тыңдау демосы</button><button class="secondary" data-author="${id}">Автор туралы</button></div><div class="rating"><label for="rating-${id}">Менің бағам</label><select id="rating-${id}" data-rating="${id}"><option value="0">Баға беріңіз</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${Number(preferences.ratings[id])===n?'selected':''}>${'★'.repeat(n)} (${n}/5)</option>`).join('')}</select><small>Баға осы браузерде сақталады.</small></div>`);};
function reader(id,page=Number(preferences.progress[id]||0)){page=Math.max(0,Math.min(samplePages.length-1,page));preferences.progress[id]=page;remember();const book=books.find(b=>b.id===id);feature(`<div class="eyebrow">ОҚУ ДЕМОСЫ · ТҮПНҰСҚА МӘТІН ЕМЕС</div><h2>${htmlSafe(book.title)}</h2><div class="reader-tools"><label>Қаріп <select id="reader-font">${[16,18,22,26].map(n=>`<option ${Number(preferences.font)===n?'selected':''} value="${n}">${n}px</option>`).join('')}</select></label><button class="secondary" id="reader-theme">${preferences.theme==='dark'?'☀ Күндізгі':'☾ Түнгі'} режим</button></div><div class="reader-page ${preferences.theme==='dark'?'dark':''}" style="font-size:${[16,18,22,26].includes(Number(preferences.font))?preferences.font:18}px">${samplePages[page]}</div><div class="reader-pagination"><button class="secondary" data-page="${page-1}" data-book="${id}" ${page===0?'disabled':''}>← Алдыңғы</button><span>${page+1} / ${samplePages.length}</span><button class="secondary" data-page="${page+1}" data-book="${id}" ${page===samplePages.length-1?'disabled':''}>Келесі →</button></div><p class="dialog-note">Оқыған бетіңіз автоматты түрде сақталады.</p>`);document.querySelector('#reader-font').onchange=e=>{preferences.font=Number(e.target.value);reader(id,page);};document.querySelector('#reader-theme').onclick=()=>{preferences.theme=preferences.theme==='dark'?'light':'dark';reader(id,page);};}
function audio(id){feature(`<div class="eyebrow">ТЫҢДАУ ДЕМОСЫ</div><h2>${htmlSafe(books.find(b=>b.id===id).title)}</h2><p>Бұл кәсіби аудиокітап емес. Браузер демонстрациялық мәтінді дауыстап оқиды. Қазақша дауыс қолжетімділігі құрылғыңызға байланысты.</p><label class="audio-speed">Жылдамдық <select id="audio-speed"><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option></select></label><div class="feature-actions"><button class="primary" id="audio-play">▶ Тыңдау</button><button class="secondary" id="audio-pause">Үзіліс</button><button class="secondary" id="audio-stop">Тоқтату</button></div><p id="audio-status" role="status">Дайын</p>`);if(!('speechSynthesis'in window)){document.querySelector('#audio-status').textContent='Бұл браузерде дауыстап оқу қолжетімсіз.';document.querySelectorAll('#feature-content button').forEach(b=>b.disabled=true);return;}const synth=window.speechSynthesis;document.querySelector('#audio-play').onclick=()=>{if(synth.paused){synth.resume();return;}synth.cancel();const u=new SpeechSynthesisUtterance(samplePages.join(' '));u.lang='kk-KZ';u.rate=Number(document.querySelector('#audio-speed').value);const voice=synth.getVoices().find(v=>v.lang.startsWith('kk'));if(voice)u.voice=voice;u.onstart=()=>{const el=document.querySelector('#audio-status');if(el)el.textContent='Оқылып жатыр…';};u.onend=()=>{const el=document.querySelector('#audio-status');if(el)el.textContent='Тыңдау аяқталды';};u.onerror=()=>{const el=document.querySelector('#audio-status');if(el)el.textContent='Дауыс қолжетімсіз. Құрылғыңыздың дауыс баптауларын тексеріңіз.';};synth.speak(u);};document.querySelector('#audio-pause').onclick=()=>{synth.pause();document.querySelector('#audio-status').textContent='Үзіліс';};document.querySelector('#audio-stop').onclick=()=>{synth.cancel();document.querySelector('#audio-status').textContent='Тоқтатылды';};}
function authors(){const names=[...new Set(books.map(b=>b.author))];feature(`<div class="eyebrow">ӘДЕБИЕТ ӘЛЕМІ</div><h2>Авторлар</h2><label class="search"><input id="author-search" type="search" placeholder="Авторды іздеу" aria-label="Авторды іздеу"></label><div id="author-results"></div>`);const draw=q=>document.querySelector('#author-results').innerHTML=names.filter(n=>n.toLocaleLowerCase().includes(q.toLocaleLowerCase())).map(n=>{const list=books.filter(b=>b.author===n);return `<button class="author-row" data-author="${list[0].id}"><span>${htmlSafe(n)}</span><small>${list.length} кітап →</small></button>`;}).join('')||'<p>Автор табылмады.</p>';draw('');document.querySelector('#author-search').oninput=e=>draw(e.target.value);}
function author(id){const name=books.find(b=>b.id===id).author;feature(`<div class="eyebrow">АВТОР КАТАЛОГЫ</div><h2>${htmlSafe(name)}</h2><p>Осы автордың каталогтағы кітаптары</p>${books.filter(b=>b.author===name).map(b=>`<button class="author-row" data-feature-book="${b.id}"><span>${htmlSafe(b.title)}</span><small>${b.available} дана қолжетімді →</small></button>`).join('')}`);}
function profile(){feature(`<div class="eyebrow">ЖЕКЕ КАБИНЕТ ДЕМОСЫ</div><h2>${preferences.name?escapeText(preferences.name):'Оқырман кабинеті'}</h2><p>Бұл жергілікті профиль. Серверлік тіркелгі немесе құпиясөз арқылы кіру әзірге қосылмаған.</p><form id="profile-form"><label>Оқырман аты<input id="profile-name" maxlength="60" required value="${escapeText(preferences.name)}" placeholder="Атыңыз"></label><button class="primary" type="submit">Сақтау</button></form><div class="profile-stats"><span><strong>${state.saved.length}</strong> Сақталған кітап</span><span><strong>${state.orders.length}</strong> Демо тапсырыс</span><span><strong>${Object.keys(preferences.progress).length}</strong> Оқу демосы</span></div><h3>Оқуды жалғастыру</h3>${Object.entries(preferences.progress).filter(([id])=>books.some(b=>b.id===Number(id))).map(([id,page])=>`<button class="author-row" data-read="${id}"><span>${htmlSafe(books.find(b=>b.id===Number(id)).title)}</span><small>${Number(page)+1} / 3 бет →</small></button>`).join('')||'<p>Оқу демосын кітап бетінен ашыңыз.</p>'}`);document.querySelector('#profile-form').onsubmit=e=>{e.preventDefault();preferences.name=document.querySelector('#profile-name').value.trim().slice(0,60);remember();profile();toast('Оқырман аты сақталды');};}
document.querySelector('header nav').insertAdjacentHTML('beforeend','<button class="nav-feature" id="authors-open">Авторлар</button><button class="nav-feature" id="profile-open">Жеке кабинет</button>');
document.querySelector('#authors-open').onclick=authors;document.querySelector('#profile-open').onclick=profile;
document.addEventListener('click',e=>{const r=e.target.closest('[data-read]');if(r)reader(Number(r.dataset.read));const a=e.target.closest('[data-audio]');if(a)audio(Number(a.dataset.audio));const au=e.target.closest('[data-author]');if(au)author(Number(au.dataset.author));const page=e.target.closest('[data-page]');if(page)reader(Number(page.dataset.book),Number(page.dataset.page));const book=e.target.closest('[data-feature-book]');if(book){extra.close();openBook(Number(book.dataset.featureBook));}});
document.addEventListener('change',e=>{if(e.target.matches('[data-rating]')){const id=e.target.dataset.rating;const n=Number(e.target.value);if(n)preferences.ratings[id]=n;else delete preferences.ratings[id];remember();toast('Баға сақталды');}});
