const {parseRoster}=require('./roster');
module.exports=function school(db,catalog,createUser,body,reply){
for(const [name,type] of [['classroom',"TEXT NOT NULL DEFAULT ''"],['display_login',"TEXT NOT NULL DEFAULT ''"]])if(!db.prepare('PRAGMA table_info(users)').all().some(c=>c.name===name))db.exec(`ALTER TABLE users ADD COLUMN ${name} ${type}`);
db.exec('CREATE TABLE IF NOT EXISTS loans(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,book_id INTEGER NOT NULL,book_title TEXT NOT NULL,borrowed INTEGER NOT NULL,due INTEGER NOT NULL,returned INTEGER)');
return async function(req,res,url,u){const route=url.pathname;if(!['/api/school','/api/loans','/api/roster/preview','/api/roster/import'].includes(route)&&!/^\/api\/loans\/\d+\/return$/.test(route))return false;if(!u){reply(res,401,{error:'Аккаунтқа кіріңіз.'});return true;}
if(route==='/api/school'&&req.method==='GET'){const students=db.prepare("SELECT users.id,users.name,users.classroom,COUNT(DISTINCT CASE WHEN returned IS NOT NULL THEN book_id END) completed,COUNT(CASE WHEN loans.id IS NOT NULL AND returned IS NULL THEN 1 END) active FROM users LEFT JOIN loans ON users.id=loans.user_id WHERE role='student' GROUP BY users.id").all().map(s=>({...s,score:s.completed*10})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));let lastScore=null,rank=0;students.forEach((s,i)=>{if(s.score!==lastScore)rank=i+1;s.rank=rank;lastScore=s.score;});const groups=new Map();for(const s of students){const key=s.classroom||'Сыныбы көрсетілмеген';const c=groups.get(key)||{name:key,students:0,completed:0,score:0};c.students++;c.completed+=s.completed;c.score+=s.score;groups.set(key,c);}const classes=[...groups.values()].sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name));lastScore=null;rank=0;classes.forEach((c,i)=>{if(c.score!==lastScore)rank=i+1;c.rank=rank;lastScore=c.score;c.average=Number((c.score/c.students).toFixed(1));});reply(res,200,{students,classes,rule:'Кітапханашы қайтарылған деп тіркеген әр бөлек кітапқа 10 ұпай. Бір кітапты қайталап алу ұпай қоспайды.'});return true;}
if(route==='/api/loans'&&req.method==='GET'){const requested=Number(url.searchParams.get('student')||u.id);if(u.role!=='admin'&&requested!==u.id){reply(res,403,{error:'Басқа оқушы тарихына рұқсат жоқ.'});return true;}reply(res,200,db.prepare('SELECT loans.*,users.name,users.classroom FROM loans JOIN users ON users.id=loans.user_id WHERE user_id=? ORDER BY loans.id DESC').all(requested).map(l=>({...l,status:l.returned?'returned':l.due<Date.now()?'overdue':'borrowed'})));return true;}
if(u.role!=='admin'){reply(res,403,{error:'Тек кітапханашыға рұқсат.'});return true;}
if((route==='/api/roster/preview'||route==='/api/roster/import')&&req.method==='POST'){const v=await body(req);if(typeof v.document!=='string'||v.document.length>700000)throw Error('DOCX құжаты тым үлкен.');const rows=parseRoster(Buffer.from(v.document,'base64'));for(const r of rows){const old=db.prepare('SELECT * FROM users WHERE login=?').get(r.login.toLowerCase());if(old&&(old.name!==r.name||old.role!=='student'||(old.classroom&&old.classroom!==r.classroom)))throw Error('Логин қайшылығы бар: '+r.login);r.exists=!!old;}if(route.endsWith('preview'))reply(res,200,{rows});else{let added=0;for(const r of rows){if(!r.exists){await createUser({name:r.name,login:r.login,password:r.login},'student');added++;}db.prepare('UPDATE users SET classroom=?,display_login=? WHERE login=?').run(r.classroom,r.login,r.login.toLowerCase());}reply(res,200,{added,skipped:rows.length-added,total:rows.length});}return true;}
if(route==='/api/loans'&&req.method==='POST'){const v=await body(req);const student=db.prepare("SELECT id FROM users WHERE id=? AND role='student'").get(Number(v.student));const c=catalog(),b=c.books.find(b=>b.id===Number(v.book));if(!student||!b)throw Error('Оқушы немесе кітап табылмады.');if(b.available<1)throw Error('Қолжетімді дана жоқ.');if(db.prepare('SELECT id FROM loans WHERE user_id=? AND book_id=? AND returned IS NULL').get(student.id,b.id))throw Error('Бұл кітап оқушыда бар.');const due=v.due?Date.parse(v.due+'T23:59:59+05:00'):Date.now()+14*86400000;if(!Number.isFinite(due)||due<Date.now())throw Error('Қайтару мерзімі қате.');db.exec('BEGIN IMMEDIATE');try{b.available--;db.prepare('UPDATE config SET value=? WHERE key=?').run(JSON.stringify(c),'catalog');db.prepare('INSERT INTO loans(user_id,book_id,book_title,borrowed,due) VALUES(?,?,?,?,?)').run(student.id,b.id,b.title,Date.now(),due);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}reply(res,201,{ok:true});return true;}
const m=route.match(/^\/api\/loans\/(\d+)\/return$/);if(m&&req.method==='POST'){const loan=db.prepare('SELECT * FROM loans WHERE id=?').get(Number(m[1]));if(!loan)throw Error('Кітап беру жазбасы табылмады.');if(loan.returned)throw Error('Кітап бұрын қайтарылған.');const c=catalog(),b=c.books.find(b=>b.id===loan.book_id);if(!b)throw Error('Кітап каталогта жоқ.');if(b.available>=b.total)throw Error('Қор саны сәйкес емес.');db.exec('BEGIN IMMEDIATE');try{b.available++;db.prepare('UPDATE config SET value=? WHERE key=?').run(JSON.stringify(c),'catalog');db.prepare('UPDATE loans SET returned=? WHERE id=?').run(Date.now(),loan.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}reply(res,200,{ok:true});return true;}reply(res,405,{error:'Әдіс қолжетімсіз.'});return true;};};
